spring:
  application:
    name: chat-app-backend
  datasource:
    url: jdbc:mysql://localhost:3306/chatapp_db
    username: root
    password: Radhe123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    com.chatapp: DEBUG